"""
exporter.py

Export matched grant results to CSV or a Markdown report.
"""

import csv
import io
from datetime import date
from typing import Optional

from .grants_api import GrantOpportunity
from .profile    import NonprofitProfile


def to_csv_bytes(
    grants:  list[GrantOpportunity],
    profile: NonprofitProfile,
) -> bytes:
    """
    Export matched grants to a UTF-8 CSV suitable for download.

    Returns bytes so it can be served directly via st.download_button().
    """
    buf = io.StringIO()
    writer = csv.writer(buf)

    writer.writerow([
        "Rank", "Title", "Agency", "Grant Number",
        "Relevance Score", "Award Floor", "Award Ceiling",
        "Expected Awards", "Open Date", "Close Date",
        "Categories", "Eligible Applicants",
        "AI Rationale", "Description (truncated)",
    ])

    for i, g in enumerate(grants, 1):
        writer.writerow([
            i,
            g.title,
            g.agency,
            g.number,
            f"{g.relevance_score:.0%}",
            g.award_floor_fmt,
            g.award_ceiling_fmt,
            g.expected_awards or "N/A",
            g.open_date or "",
            g.close_date or "",
            "; ".join(g.categories),
            "; ".join(g.eligible_types),
            g.score_breakdown.get("ai_rationale", ""),
            g.description[:300].replace("\n", " "),
        ])

    return buf.getvalue().encode("utf-8")


def to_markdown_report(
    grants:   list[GrantOpportunity],
    profile:  NonprofitProfile,
    top_n:    int = 10,
) -> str:
    """
    Generate a Markdown grant report suitable for sharing with leadership.
    """
    today = date.today().strftime("%B %d, %Y")
    lines = [
        f"# Grant Opportunity Report",
        f"**Organization:** {profile.name}  ",
        f"**Generated:** {today}  ",
        f"**Opportunities matched:** {len(grants)}  ",
        "",
        "---",
        "",
        f"## Top {min(top_n, len(grants))} Matches",
        "",
    ]

    for i, g in enumerate(grants[:top_n], 1):
        score_pct = f"{g.relevance_score:.0%}"
        rationale = g.score_breakdown.get("ai_rationale", "")

        lines += [
            f"### {i}. {g.title}",
            f"**Agency:** {g.agency}  ",
            f"**Grant #:** {g.number}  ",
            f"**Relevance:** {score_pct}  ",
            f"**Award Range:** {g.award_floor_fmt} – {g.award_ceiling_fmt}  ",
            f"**Deadline:** {g.deadline_display}  ",
            f"**Categories:** {', '.join(g.categories) or 'N/A'}  ",
            f"**Eligible:** {', '.join(g.eligible_types) or 'N/A'}  ",
            "",
        ]
        if rationale:
            lines += [f"> {rationale}", ""]
        lines += [
            f"{g.description[:400]}{'…' if len(g.description) > 400 else ''}",
            "",
            "---",
            "",
        ]

    lines += [
        "## Profile Used",
        f"**Mission:** {profile.mission}  ",
        f"**Focus Areas:** {', '.join(profile.focus_areas)}  ",
        f"**Populations:** {', '.join(profile.populations)}  ",
        "",
        "*Report generated by Grant Opportunity Matcher — github.com/DCodeBase-X/grant-opportunity-matcher*",
    ]

    return "\n".join(lines)
